# See NOTE comments for places to modify.
services:

  frontend:
    image: unmute-frontend:latest
    build:
      context: frontend-custom/
      dockerfile: hot-reloading.Dockerfile
    volumes:
      - ./frontend-custom/src:/app/src
    environment:
      - NEXT_PUBLIC_IN_DOCKER=false
    ports:
      - "3000:3000"

  backend:
    image: unmute-backend:latest
    build:
      context: backend-custom/
      target: hot-reloading
    volumes:
      - ./backend-custom/unmute:/app/unmute
    environment:
      - KYUTAI_STT_URL=ws://stt:8080
      - KYUTAI_TTS_URL=ws://tts:8080
      - KYUTAI_LLM_URL=${KYUTAI_LLM_URL}
      - KYUTAI_LLM_MODEL=${KYUTAI_LLM_MODEL}
      - KYUTAI_LLM_API_KEY=${KYUTAI_LLM_API_KEY}
    ports:
      - "8000:80"
    labels:
      - "prometheus-port=80"

  tts:
    image: moshi-server:latest
    command: ["worker", "--config", "configs/tts-custom.toml"]
    build:
      context: services/moshi-server
      dockerfile: public_custom.Dockerfile
      args:
        CUDA_COMPUTE_CAP: "80"
    volumes:
      - ./volumes/hf-cache:/root/.cache/huggingface
      - ./volumes/tts-logs:/tmp/unmute_logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

  stt:
    image: moshi-server:latest
    command: ["worker", "--config", "configs/stt.toml"]
    build:
      context: services/moshi-server
      dockerfile: public_custom.Dockerfile
      args:
        CUDA_COMPUTE_CAP: "80"
    volumes:
      - ./volumes/hf-cache:/root/.cache/huggingface
      - ./volumes/stt-logs:/tmp/unmute_logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

networks:
  default:
